# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit wilas_relatorio.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  echo = FALSE, # não mostra ro código
  eval = TRUE, # executar o código
  fig.cap = "", # título do gráfico
  results = "asis", # formato de renderização de texto
  fig.width = 8, # largura do gráfico
  fig.height = 4, # altura do gráfico
  fig.align = "center", # alinhamento horizontal do gráfico
  out.width = "100%", # redimensionamento do gráfico (aumentar/diminuir em %)
  warning = FALSE, # exibir avisos do console
  message = FALSE # exibir mensagens do console
  )
library(tidyverse)
library(knitr)
library(readxl)
library(tidyr)
library(dplyr)
library(rmarkdown)
library(scales)
library(png)
library(stevemisc)

#pak::pak("rstudio/rticles")



## ----tab1, echo=F, eval=TRUE, message=F, warning=F----------------------------
library(knitr)
source("script_relatorio.R", local = F)

knitr::kable(Pop_sex_Rmed, 
    caption = "\\label{tab1}Total da População por Sexo em Aracaju e Renda Média, 2022.1 a 2023.1", align = "ccccr")


#knitr::kable(Pop_sex, format = "html", align = "cccc", digits = getOption("digits"), format.args = list(big.mark = "."))



## ----tab2, echo = F, eval=TRUE, message=F, warning=F--------------------------
library(knitr)

knitr::kable(PEA_NPEA_ocup_des_desal, 
    caption = "\\label{tab2}População na Força de Trabalho, Fora da Força de Trabalho, Ocupada, Desocupada e em Desalento em Aracaju, 2022.1 a 2023.1", align = "c")

#knitr::kable(Pop_sex, format = "html", align = "cccc", digits = getOption("digits"), format.args = list(big.mark = "."))



## ----tab3, echo = F, eval=TRUE, message=F, warning=F--------------------------
knitr::kable(T_estuda, 
    caption = "\\label{tab3}Pessoas que Estudam em Aracaju, 2022.1 a 2023.1", align = "c")



## ----tab4, echo = F, eval=TRUE, message=F, warning=F--------------------------
library(knitr)

source("script_relatorio.R", local = F)
#source('script_relatorio.R')

knitr::kable(T_estDes, 
    caption = "\\label{tab4}Pessoas Ocupadas e Desocupadas que Estudam e Não Estudam em Aracaju, 2022.4 a 2023.1", align = "c")

#knitr::kable(Pop_sex, format = "html", align = "cccc", digits = getOption("digits"), format.args = list(big.mark = "."))



## ----tab5, echo = F, eval=TRUE, message=F, warning=F--------------------------
knitr::kable(Instr, 
    caption = "\\label{tab5}População por Nivel de Instrução em Aracaju, 2022.4 a 2023.1", align = "lcc")



## ----tab6, echo = F, eval=TRUE, message=F, warning=F--------------------------
knitr::kable(ins_n_est, 
    caption = "\\label{tab6}Nivel de Instrução das Pessoas que Não Estudam em Aracaju, 2022.4 a 2023.1", align = "lcc")



## ----tab7, echo = F, eval=TRUE, message=F, warning=F--------------------------
knitr::kable(T_nem_nem, 
    caption = "\\label{tab7}Nem Estudam e Nem Trabalham por Nivel de Instrução em Aracaju, 2022.4 a 2023.1", align = "lcc")



## ----tab8, echo = F, eval=TRUE, message=F, warning=F--------------------------
library(knitr)

knitr::kable(desocupfaixa, 
    caption = "\\label{tab8}Ocupação e Desocupação por Faixa Etária em Aracaju, 2022.4 a 2023.1", align = "c")

#knitr::kable(Pop_sex, format = "html", align = "cccc", digits = getOption("digits"), format.args = list(big.mark = "."))



## ----tab9, echo = F, eval=TRUE, message=F, warning=F--------------------------
knitr::kable(esc_des_faAJ, 
    caption = "\\label{tab9}Jovens Desocupados por Nivel de Instrução em Aracaju, 2022.4 a 2023.1", align = "clccc")



## ----tab10, echo = F, eval=TRUE, message=F, warning=F-------------------------
knitr::kable(nem_nem_fa_des, 
    caption = "\\label{tab10}Jovens Nem-Nem por Nivel de Instrução em Aracaju, 2022.4 a 2023.1", align = "clccc")



## ----tab11, echo = F, eval=TRUE, message=F, warning=F-------------------------
knitr::kable(OcupsetorAJ, 
    caption = "\\label{tab11}Pessoas Ocupadas por Setor Produtivo em Aracaju, 2022.4 a 2023.1", align = "lcc")



## ----tab12, echo = F, eval=TRUE, message=F, warning=F-------------------------
knitr::kable(Rmed_Setor, 
    caption = "\\label{tab12}Renda Média por Setor em Aracaju, 2022.4 a 2023.1", align = "lcc")


